//! Common event envelope — every observation the agent collects becomes an Event.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Every raw observation collected by the agent.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Event {
    /// Unique event ID (generated by agent).
    pub id: Uuid,
    /// Agent that generated this event.
    pub agent_id: String,
    /// UTC timestamp when the event was observed.
    pub timestamp: DateTime<Utc>,
    /// Category of the event.
    pub event_type: EventType,
    /// Source that produced this event (e.g. "sysmon", "security_log", "powershell").
    pub source: String,
    /// Sysmon/Security event ID, if applicable.
    pub event_id: Option<u32>,
    /// Free-form payload with all event-specific fields.
    pub payload: serde_json::Value,
}

impl Event {
    pub fn new(
        agent_id: &str,
        event_type: EventType,
        source: &str,
        event_id: Option<u32>,
        payload: serde_json::Value,
    ) -> Self {
        Self {
            id: Uuid::new_v4(),
            agent_id: agent_id.to_string(),
            timestamp: Utc::now(),
            event_type,
            source: source.to_string(),
            event_id,
            payload,
        }
    }
}

/// Categories matching the PDF telemetry sources.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum EventType {
    /// Process creation/termination (Sysmon 1, 5)
    Process,
    /// Network connection (Sysmon 3)
    Network,
    /// DNS query (Sysmon 22)
    Dns,
    /// Driver/image load (Sysmon 7)
    DriverLoad,
    /// File system event (Sysmon 11/23)
    FileSystem,
    /// Authentication event (Security log 4624/4625)
    Auth,
    /// PowerShell script block (Event 4104)
    PowerShell,
    /// Registry event (Sysmon 12/13)
    Registry,
    /// Pipe event (Sysmon 17/18)
    Pipe,
}
