//! Common event envelope — every observation the agent collects becomes an Event.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::risk::{InvariantViolation, RiskFlag};

/// Every raw observation collected by the agent.
///
/// Wire format note: `risk_flags`, `risk_score`, and `invariant_violation` are
/// additive fields produced by the agent's local classifier (§4.5 of the agent
/// specification). They are skipped during serialization when empty/zero/None,
/// so legacy backends that don't understand them see the same payload as before.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Event {
    /// Unique event ID (generated by agent).
    pub id: Uuid,
    /// Agent that generated this event.
    pub agent_id: String,
    /// UTC timestamp when the event was observed.
    pub timestamp: DateTime<Utc>,
    /// Category of the event.
    pub event_type: EventType,
    /// Source that produced this event (e.g. "sysmon", "security_log", "powershell").
    pub source: String,
    /// Sysmon/Security event ID, if applicable.
    #[serde(rename = "original_event_id", alias = "event_id")]
    pub event_id: Option<u32>,
    /// Free-form payload with all event-specific fields.
    pub payload: serde_json::Value,

    /// Local risk indicators attached by the classifier.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub risk_flags: Vec<RiskFlag>,

    /// Aggregate score, 0..=100. 0 means "no local concern".
    #[serde(default, skip_serializing_if = "is_zero_u8")]
    pub risk_score: u8,

    /// Set when the event tripped one of the policy invariants (§4.5.1).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub invariant_violation: Option<InvariantViolation>,

    /// Names of detection filters (from policy) that matched this event.
    /// Populated when a filter's action is "flag". Empty when no filter matched.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub matched_filters: Vec<String>,
}

fn is_zero_u8(v: &u8) -> bool {
    *v == 0
}

impl Event {
    pub fn new(
        agent_id: &str,
        event_type: EventType,
        source: &str,
        event_id: Option<u32>,
        payload: serde_json::Value,
    ) -> Self {
        Self {
            id: Uuid::new_v4(),
            agent_id: agent_id.to_string(),
            timestamp: Utc::now(),
            event_type,
            source: source.to_string(),
            event_id,
            payload,
            risk_flags: Vec::new(),
            risk_score: 0,
            invariant_violation: None,
            matched_filters: Vec::new(),
        }
    }
}

/// Categories matching the PDF telemetry sources.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum EventType {
    /// Process creation/termination (Sysmon 1, 5)
    Process,
    /// Network connection (Sysmon 3)
    Network,
    /// DNS query (Sysmon 22)
    Dns,
    /// Kernel driver loaded (Sysmon 6) — feeds invariants.unsigned_drivers
    DriverLoad,
    /// Image/DLL loaded into a process (Sysmon 7)
    ImageLoad,
    /// File system event (Sysmon 2, 11, 15, 23)
    FileSystem,
    /// Authentication event (Security log 4624/4625)
    Auth,
    /// PowerShell script block (Event 4104)
    PowerShell,
    /// Registry event (Sysmon 12, 13)
    Registry,
    /// Pipe event (Sysmon 17, 18)
    Pipe,
    /// WMI activity events (Sysmon 19, 20, 21)
    WmiActivity,
    /// Clipboard change event (Sysmon 24)
    ClipboardAccess,
    /// Raw disk access event (Sysmon 9)
    RawDiskAccess,
    /// Process handle access (Sysmon 10) — feeds invariants.credential_dumping
    ProcessAccess,
    /// Remote thread injection (Sysmon 8)
    RemoteThread,
}
